### ISSUE TITLE
Need to replace the PDF with a Word Doc

### ISSUE THREAD

**Issue by dronca** [Netflix/vp9-dash#7]
In order to facilitate edits and change tracking, need to shift from PDF to Word doc.

**Comment by dronca** [comment]
[Delete PDF](https://github.com/Netflix/vp9-dash/commit/5cc4bce0941a0950733e816421cacf2a416f8e2b)

**Comment by dronca** [comment]
[Add Word Doc](https://github.com/Netflix/vp9-dash/commit/3ca1fca84e3025d1b9bfd772a26f9475179a8b7a)

**Comment by kodawah** [comment]
This is such a bad idea, doc is a binary closed format that cannot be opened on a variety of devices!

Can you use an open format such as Markdown (can be read and edited as plain text) or odf? At the very least you should keep a pdf version around for easier distribution.

**Comment by kodawah** [comment]
Allow me to add that being under revision control, a binary file is _much_ harder to check for revisions and understand what changed.
